"""add monk configs, trades, pipeline runs tables

Revision ID: 15f894677995
Revises: a1994b723c4d
Create Date: 2026-04-11 23:22:53.517761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15f894677995'
down_revision: Union[str, Sequence[str], None] = 'a1994b723c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monk_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('deployment_mode', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monk_configs_family_id'), 'monk_configs', ['family_id'], unique=False)
    op.create_index(op.f('ix_monk_configs_name'), 'monk_configs', ['name'], unique=False)
    op.create_table('monk_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('monk_name', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=256), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monk_trades_monk_name'), 'monk_trades', ['monk_name'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_monk_trades_monk_name'), table_name='monk_trades')
    op.drop_table('monk_trades')
    op.drop_index(op.f('ix_monk_configs_name'), table_name='monk_configs')
    op.drop_index(op.f('ix_monk_configs_family_id'), table_name='monk_configs')
    op.drop_table('monk_configs')
    # ### end Alembic commands ###
