"""create raw ingestion tables

Revision ID: 3145aa1d37cd
Revises: 
Create Date: 2026-04-11 21:31:14.534832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3145aa1d37cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingest_id', sa.String(length=64), nullable=False),
    sa.Column('ingest_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_count', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingest_id')
    )
    op.create_table('raw_event_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingest_id', sa.String(length=64), nullable=False),
    sa.Column('event_ticker', sa.String(length=256), nullable=False),
    sa.Column('series_ticker', sa.String(length=256), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_event_snapshots_ingest_id'), 'raw_event_snapshots', ['ingest_id'], unique=False)
    op.create_index('ix_raw_event_ticker_ingested', 'raw_event_snapshots', ['event_ticker', 'ingested_at'], unique=False)
    op.create_table('raw_market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingest_id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=256), nullable=False),
    sa.Column('event_ticker', sa.String(length=256), nullable=True),
    sa.Column('series_ticker', sa.String(length=256), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_market_snapshots_ingest_id'), 'raw_market_snapshots', ['ingest_id'], unique=False)
    op.create_index('ix_raw_market_ticker_ingested', 'raw_market_snapshots', ['ticker', 'ingested_at'], unique=False)
    op.create_table('raw_series_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingest_id', sa.String(length=64), nullable=False),
    sa.Column('series_ticker', sa.String(length=256), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_series_snapshots_ingest_id'), 'raw_series_snapshots', ['ingest_id'], unique=False)
    op.create_index('ix_raw_series_ticker_ingested', 'raw_series_snapshots', ['series_ticker', 'ingested_at'], unique=False)
    op.create_table('raw_trade_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingest_id', sa.String(length=64), nullable=False),
    sa.Column('trade_id', sa.String(length=128), nullable=False),
    sa.Column('ticker', sa.String(length=256), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_trade_snapshots_ingest_id'), 'raw_trade_snapshots', ['ingest_id'], unique=False)
    op.create_index('ix_raw_trade_ticker_ingested', 'raw_trade_snapshots', ['ticker', 'ingested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_trade_ticker_ingested', table_name='raw_trade_snapshots')
    op.drop_index(op.f('ix_raw_trade_snapshots_ingest_id'), table_name='raw_trade_snapshots')
    op.drop_table('raw_trade_snapshots')
    op.drop_index('ix_raw_series_ticker_ingested', table_name='raw_series_snapshots')
    op.drop_index(op.f('ix_raw_series_snapshots_ingest_id'), table_name='raw_series_snapshots')
    op.drop_table('raw_series_snapshots')
    op.drop_index('ix_raw_market_ticker_ingested', table_name='raw_market_snapshots')
    op.drop_index(op.f('ix_raw_market_snapshots_ingest_id'), table_name='raw_market_snapshots')
    op.drop_table('raw_market_snapshots')
    op.drop_index('ix_raw_event_ticker_ingested', table_name='raw_event_snapshots')
    op.drop_index(op.f('ix_raw_event_snapshots_ingest_id'), table_name='raw_event_snapshots')
    op.drop_table('raw_event_snapshots')
    op.drop_table('ingest_log')
    # ### end Alembic commands ###
