"""add strategy_blueprint to monk_configs

Revision ID: 7a93158406d6
Revises: 15f894677995
Create Date: 2026-04-11 23:58:08.821758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a93158406d6'
down_revision: Union[str, Sequence[str], None] = '15f894677995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monk_configs', sa.Column('strategy_blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monk_configs', 'strategy_blueprint')
    # ### end Alembic commands ###
